### PR TITLE
Fixed: Empty Sketch document opening in background when run via Sketchtool 

### PR DESCRIPTION
**Pull request by atalun**
When run via Sketchtool the additional empty Sketch document is being opened. This means that:

- the additional Sketch instances are being opened which wastes memory and clutters the taskbar (especially in our use case where we run this command on every save)

- the plugin gets confused about the preview paths somehow and just dosn't export the preview images which stops prototype from running.

I found out that in file "cmdline-functions.js" in line 73 code:

    var document = new Document()

Does exactly that. I removed it and the "ghost" instances stopped popping out and export works every time. Do not see any reason for this line to exist.

### CODE REVIEW

**Comment by MaxBazarov** [comment]
> When run via Sketchtool the additional empty Sketch document is being opened. This means that:
> 
> * the additional Sketch instances are being opened which wastes memory and clutters the taskbar (especially in our use case where we run this command on every save)
> * the plugin gets confused about the preview paths somehow and just dosn't export the preview images which stops prototype from running.
> 
> I found out that in file "cmdline-functions.js" in line 73 code:
> 
> ```
> var document = new Document()
> ```
> 
> Does exactly that. I removed it and the "ghost" instances stopped popping out and export works every time. Do not see any reason for this line to exist.


Wow!  Before your patch I need to kill all Sketch instances after exporting.
Will include it into the next update.

Thank!

**Comment by MaxBazarov** [comment]
It's not easy to review your patch because your text editor does many non-required formatting. Could you somehow disable it?

**Comment by atalun** [comment]
Ok, I use Visual Studio code with js plugin which is linting code on every save. I can dissable it but perhaps it's good idea to lint the whole project to some agreed specs? But anyways, I will close this PR and open new one when I provide fix with just that one change.

**Comment by MaxBazarov** [comment]
I pushed already this one change manually.

Yes, it's a good idea to link the whole project. What VSC plugin are you using?

**Comment by atalun** [comment]
Oh, that's great.
I use https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by MaxBazarov** [comment]
@atalun I'm trying to setup ESLint. It asks me - what code style guide will I use?
https://codeburst.io/5-javascript-style-guides-including-airbnb-github-google-88cbc6b2b7aa
What are you using?

**Comment by atalun** [comment]
@MaxBazarov it depends on You, really. I do not hold any strong opinions (I do not consider myself as JS developer) but any style guide is better than none. The Airbnb style seems to be based on common sense and is quite popular. The "standard" one has the advantage of having it's own command (great for making sure everyone have the same configuration).

**Pull request closed without merging**
